### ISSUE TITLE
IP Address

### ISSUE THREAD

**Issue by CaptGreenbean** [k01ek/netbox-qrcode#13]
Is it possible to display the IP address of a device with the other text information so that it can be printed with the QR code? If not, is that something that can be easily added? Thanks!

**Comment by k01ek** [comment]
hi @CaptGreenbean! It is possible. You need to add field `primary_ip` to text_fields configuration for device. For example:
```
PLUGINS_CONFIG = {
    'netbox_qrcode': {
        'with_text': True,
        'device': {
            'text_fields': ['name', 'serial', 'primary_ip']
        }
    }
}
```
