### ISSUE TITLE
Documentation: Use Cases?

### ISSUE THREAD

**Issue by adamwoolhether** [k01ek/netbox-qrcode#2]
Is there any information regarding specific use cases for the QR codes? Where does scanning the QR codes actually direct the user? I think this plugin is extremely cool, but I lack the know-how to actually utilize it, or how it can be used.

**Comment by k01ek** [comment]
HI @adamwoolhether ! Sry for late response... The use case can be any that you can imagine. For example, it is a quick navigation in machine room. You can print and put  label on any object: rack, server, network device, cable, etc, and then using phone or tablet  quickly get info about those objects.
Honestly, we don't use this plugin in production environment. So this plugin was built just for fun and for getting experience.

**Comment by adamwoolhether** [comment]
@k01ek Very cool, thanks. I think it's quite useful for this.

I'm always pondering the idea of trying to automate the Rack_U placement of servers within netbox, may be out of my expertise, but QR Codes were one of the potential solutions I was exploring. WIll let you know if we use your Plugin :D.
