### ISSUE TITLE
502 bad gateway error

### ISSUE THREAD

**Issue by i-pushkin** [k01ek/netbox-qrcode#22]
I used netbox 3.1.6 version on debian 10 with python3.9
After installing I receive the 502 bad gateway error. 

`2022/02/09 17:19:39 [error] 23608#23608: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 178.134.17.111, server: netbox.example.com, request: "GET / HTTP/2.0", upstream: "http://127.0.0.1:8001/", host: "netbox.example.com"
`

**Comment by andytruett** [comment]
I had the same issue and found that I didn't install netbox-qrcode to the virtual environment that Netbox is using.

Added it to local_requirements and ran /opt/netbox/upgrade.sh and it worked for me.
