### ISSUE TITLE
Adaptation installation guide "venv" required

### ISSUE THREAD

**Issue by LHBL2003** [k01ek/netbox-qrcode#24]
The installation instructions initially caused my netbox not to start.

I then saw in the instructions of Netbox that you must first activate the "virtual environment" (venv).

I therefore ask to mention that before the 
`"pip install netbox-qrcode"`

a 

`"source /opt/netbox/venv/bin/activate"`

is required.

Thanks a lot

**Comment by k01ek** [comment]
It depends on how you install NetBox. But you're right, some explanation of the readme would be helpful.
