### ISSUE TITLE
Add Static Text to Label

### ISSUE THREAD

**Issue by cyberndj** [k01ek/netbox-qrcode#29]
Hi, 
I'm wondering how I can prepend static text for a field in my instance, the rack field in devices in this case.

In our org, we label our racks with numbers (1, 1.4, 12, etc) and not "Rack 1," "Rack 1.4," "Rack 12L" etc.
The only place this is an issue for us is on the QR text in the device. We would like to prepend some text before the rack variable so the text would look something more human readable

Something like this:
'device'            ->          Switch1
'serial'              ->          F0Cisco
'location'         ->          HQ IDF B
"Rack: "'rack'   ->          Rack: 2

vs Not This
Switch1
F0Cisco
HQ IDF B
2

**Comment by k01ek** [comment]
Hi @cyberndj ! It is good feature for the next release!
