### ISSUE TITLE
Text options

### ISSUE THREAD

**Issue by steele-ntwrk** [k01ek/netbox-qrcode#30]
Is there a reference for what object can be added in a 'text_field'?

I tried 'asset_tag' but it doesnt work.

Any help would be good

**Comment by k01ek** [comment]
Hi @steele-ntwrk ! Any text fields of object can be added. If you want to add device's asset_tag try this config:
```
'text_fields': ['asset_tag'] 
```

**Comment by steele-ntwrk** [comment]
Hi @k01ek , 

That worked, it seems like my configuration file had some errors in it causing it not pass in the plugins-config.

Cheers mate!
