### ISSUE TITLE
FR: Add reading of (custom) QR codes

### ISSUE THREAD

**Issue by jbemmel** [k01ek/netbox-qrcode#36]
Some devices come with a QR code printed on them. It would be great if this plug-in could be extended to read such QR codes, and onboard the device into Netbox

As a starting point: See https://github.com/mebjas/html5-qrcode (open source HTML5 QR code reader library)

The idea would be to add HTML/web code along those lines, making it part of the Netbox UI.

Apologies if something like this already exists/is possible - I am not aware of anything like this existing today

**Comment by k01ek** [comment]
Hi @jbemmel ! QRCode,Barcode or any other *code labels on devices contain various information, mainly intended for internal purposes. I do not think that it can be useful for use in NetBox

**Comment by jbemmel** [comment]
I made a start here: https://github.com/jbemmel/netbox-qrprovision/blob/master/develop/qrdecode.js

I agree that it's different from what the current plugin does, but there are customers asking for this kind of functionality. The product code and serial number can help to map the physical device deployment to the virtual topology and the Netbox data base

**Comment by k01ek** [comment]
Can you give some examples of these codes? If they contain useful information such as serial number, manufacturer, model it can be used.

**Comment by jbemmel** [comment]
![image](https://user-images.githubusercontent.com/2031627/198024707-042542ff-3391-4b52-b403-f67c0862d64c.png)

The idea would be to make this multi-vendor: Based on the company id, lookup a plugin to handle the conversion into the Netbox data model. In this case (for example) the part number would be part of the device template, so we can look it up and create a device in the rack based on that type
