### ISSUE TITLE
URL for device management in QR?

### ISSUE THREAD

**Issue by dmidlo** [k01ek/netbox-qrcode#38]
I was wondering what the best way embed a device specific URL into the QR code?  The use-case would be that a tech can scan the QR code on their mobile device, which then opens the mobile browser and brings them to say... the device's netbox page?

**Comment by k01ek** [comment]
Hi @dmidlo ! I don't think that's good idea to configure device from mobile device. Basic idea of this plugin is easily identify device in machine room.

**Comment by dmidlo** [comment]
Netbox is a source of truth, not a configuration tool.  That's the largest part of the idea exactly.  Be logged into netbox on your mobile browser, Scan QR code on device (which opens new tab on mobile browser).  Device is identified, and tech has access to SoT about the device?

**Comment by k01ek** [comment]
From netbox device page you can easily get link for configuration, for example using custom links.
