### ISSUE TITLE
builinding docker-image is failing with python 3.9

### ISSUE THREAD

**Issue by FloMeyer** [k01ek/netbox-qrcode#4]
docker-compose build --no-cache
redis-cache uses an image, skipping
postgres uses an image, skipping
redis uses an image, skipping
netbox-worker uses an image, skipping
nginx uses an image, skipping
Building netbox
Step 1/3 : FROM netboxcommunity/netbox:latest-ldap
 ---> 08d595b37d56
Step 2/3 : copy ./plugin_requirements.txt /
 ---> 97addb913761
Step 3/3 : RUN pip3 install  --no-warn-script-location -r /plugin_requirements.txt
 ---> Running in ce2450cd63ba
Collecting netbox-qrcode
  Downloading netbox_qrcode-0.0.3-py3-none-any.whl (1.7 MB)
**Collecting Pillow==7.2.0**
  Downloading Pillow-7.2.0.tar.gz (39.1 MB)
Collecting qrcode==6.1
  Downloading qrcode-6.1-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: six in /usr/local/lib/python3.9/site-packages (from qrcode==6.1->netbox-qrcode->-r /plugin_requirements.txt (line 1)) (1.15.0)
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py): started
  Building wheel for Pillow (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-apgpq2zp
       cwd: /tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/
  Complete output (170 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/Image.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/features.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_util.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/_version.py -> build/lib.linux-x86_64-3.9/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  writing top-level names to src/Pillow.egg-info/top_level.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.ci'
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext

  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html

  Traceback (most recent call last):
    File "/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py", line 864, in <module>
      setup(
    File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py", line 694, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: zlib

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py", line 918, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:

  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html

  ----------------------------------------
  Running setup.py clean for Pillow
  ERROR: Failed building wheel for Pillow
Failed to build Pillow
Installing collected packages: qrcode, Pillow, netbox-qrcode
  Attempting uninstall: Pillow
    Found existing installation: Pillow 8.0.1
    Uninstalling Pillow-8.0.1:
      Successfully uninstalled Pillow-8.0.1
    Running setup.py install for Pillow: started
    Running setup.py install for Pillow: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0fr3p7lf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/Pillow
         cwd: /tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/
    Complete output (172 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/Image.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/features.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/_util.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/_version.py -> build/lib.linux-x86_64-3.9/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.9/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.ci'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py", line 864, in <module>
        setup(
      File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py", line 694, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py", line 918, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    ----------------------------------------
  Rolling back uninstall of Pillow
  Moving to /usr/local/lib/python3.9/site-packages/PIL/
   from /usr/local/lib/python3.9/site-packages/~IL
  Moving to /usr/local/lib/python3.9/site-packages/Pillow-8.0.1.dist-info/
   from /usr/local/lib/python3.9/site-packages/~illow-8.0.1.dist-info
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yc4ljrct/pillow_a3f862e4f02f4f4c97242bc6fd9ab973/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-0fr3p7lf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/Pillow Check the logs for full command output.
ERROR: Service 'netbox' failed to build : The command '/bin/sh -c pip3 install  --no-warn-script-location -r /plugin_requirements.txt' returned a non-zero code: 1

Is there a reason why you use Pillow 7.2?
Python3.9 needs Pillow >= 8

https://pillow.readthedocs.io/en/latest/installation.html

**Comment by FloMeyer** [comment]
I remove the versio numbers in your setup.py and built the whl package and added it as local requirement.

```
install_requires=[
        'qrcode==6.1',
        'Pillow==7.2.0'
    ],
```
to
```
install_requires=[
        'qrcode',
        'Pillow'
    ],
```

This is working, but i have an error with some characters:♦ 

 

> Server Error
> There was a problem with your request. Please contact an administrator.
> 
> The complete exception is provided below:
> 
> <class 'UnicodeEncodeError'>
> 
> 'latin-1' codec can't encode character '\u2666' in position 5: ordinal not in range(256)
> 
> Python version: 3.9.1
> NetBox version: 2.10.2
> If further assistance is required, please post to the NetBox mailing list.

**Comment by k01ek** [comment]
Hi @FloMeyer! Pillow 7.2 was the last version when I used it. I don't know if Pillow 8 is back compatible with 7.2, so It need to test. 
Concerning your second error, the reason is black diamond suit symbol in your text ('\u2666'). Try to remove it.

**Comment by FloMeyer** [comment]
> Hi @FloMeyer! Pillow 7.2 was the last version when I used it. I don't know if Pillow 8 is back compatible with 7.2, so It need to test.
> Concerning your second error, the reason is black diamond suit symbol in your text ('\u2666'). Try to remove it.

Thanks, that's true. Without this symbol its working...

**Comment by Bernardino18** [comment]
Any updates on supporting python 3 ?

**Comment by k01ek** [comment]
Did you mean python 3.9?

**Comment by k01ek** [comment]
I removed 7.2 pillow version from requirements, now python 3.9 can be used
