### ISSUE TITLE
textsize is deprecated in Pillow 10

### ISSUE THREAD

**Issue by andrege** [k01ek/netbox-qrcode#48]
Textsize is deprecated in Pillow 10, according to:
https://pillow.readthedocs.io/en/stable/deprecations.html#font-size-and-offset-methods

Resulting in the following error in the Netbox version below:

<class 'AttributeError'>

'ImageDraw' object has no attribute 'textsize'

Python version: 3.10.6
NetBox version: 3.5.5

The textsize function is used in the utilities.py file, line 43.

The (temporary) solution was to downgrade do Pillow 9.5.0.

**Comment by Trusthier** [comment]
Smae problème my side.

**Comment by miconx** [comment]
same problem here 
does anyone know a fix?

**Comment by dmcken** [comment]
For netbox-docker you can set:
```
pillow==9.5.0
```
In the plugin_requirements.txt and then ```docker compose build``` and ```docker compose up -d```

**Comment by sourceforge807** [comment]
I think in the file /utilities.py you may replace line 43 `        w, h = draw.textsize(text, font=fnt)` with`         w, h = draw.textlength(text, font=fnt)`
Releasenotes from Pillow: https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html chapter "Font size and offset methods"

**Comment by k01ek** [comment]
just quick fix for that #53

**Comment by k01ek** [comment]
fixed
