### ISSUE TITLE
Problem installing netbox-qrcode on NetBox V 3.5.7

### ISSUE THREAD

**Issue by chbally** [k01ek/netbox-qrcode#50]
I'm new in NetBox and wanted to install it on a Version V 3.5.7
I had some issus while installing, which I could solve with some chmods
Now, when I want to open Racks or Devices I get the following Fault-Side:
![grafik](https://github.com/k01ek/netbox-qrcode/assets/22587897/665a9ee7-7fcd-46ea-a6d8-f669298fe13e)
I guess it's because of a newer Pearl version.

**Comment by damo2929** [comment]
you tried using this pending pull request  as it works for me
https://github.com/k01ek/netbox-qrcode/pull/49

**Comment by chbally** [comment]
Hey damo2929,
I got QR Codes now, bit no textfields.
I use the sample PLUGIN_CONFIG:
`PLUGINS_CONFIG = {
   'netbox_qrcode': {
        'with_text': True,
        'text_fields': ['name', 'serial'],
        'font': 'ArialMT',
        'custom_text': 'Property of SomeCompany\ntel.8.800333554-CALL',
        'text_location': 'up',
        'qr_version': 1,
        'qr_error_correction': 0,
        'qr_box_size': 4,
        'qr_border': 4,
        # per object options
        'cable': None,  # disable QR code for Cable object
        'rack': {
            'text_fields': [
                'site',
                'name',
                'facility_id',
                'tenant',
                'cf.cf_name'
            ]
        },
        'device': {
            'qr_box_size': 6,
            'custom_text': None,
        }
    }
}
`

**Comment by chbally** [comment]
Thanks - that worked.
