### ISSUE TITLE
Feature Request: add qrcode to Power Feeds and Power Panels

### ISSUE THREAD

**Issue by andrege** [k01ek/netbox-qrcode#54]
I am attaching two diffs that modifies the code to include the QR code:

[__init__.txt](https://github.com/k01ek/netbox-qrcode/files/12479776/__init__.txt)
[template_content.txt](https://github.com/k01ek/netbox-qrcode/files/12479786/template_content.txt)

**Comment by mhdask** [comment]
I would also like to see this feature implemented, but i am not sure if this project is still maintained, as it seems that it is not

**Comment by k01ek** [comment]
done
