### ISSUE TITLE
Feature: QR Code to open link of rack or device

### ISSUE THREAD

**Issue by Rocker775** [k01ek/netbox-qrcode#55]
Hello.

I'm looking for your plugin and I'm wondering if it's able to generate a link to site.

I would like to print QR codes for Racks and Devices so when you get I get to DC, I would like to scan QR code on my rack from phone and it will direct open website with details of particular rack. Same goes for devices. 

Hope you understand my intentions.

Best regards.

**Comment by arcticash** [comment]
I'm not sure what the ask is here - that is exactly what the plugin currently does!

Have you tried installing the plugin to test it out?

**Comment by Rocker775** [comment]
I had some issues and now I went trough all and yes, it works like I was expecting. Sorry for misunderstanding. it works like a charm. Thank you
