### ISSUE TITLE
Adding a logo in the QR-code

### ISSUE THREAD

**Issue by MagnusOren** [k01ek/netbox-qrcode#61]
Hi.
Im pretty new to Linux and python. I have an issue with trying to add a logo in the qr-code. I have tried to figure it out, by changing   img = qr.make_image(), to  img = qr.make_image(image_factory=StyledPilImage, embeded_image_path="/opt/netbox/netbox/media/image-attachments/Logotoppsort.png") in the utilities.py, but im not getting it to work. Does anybody know what im doing wrong?

**Comment by MagnusOren** [comment]
I got it to work, when i foud the right file to change.

**Comment by MarkusBe** [comment]
Would be great to know a little bit more specific what was the right location... Thx!

**Comment by MagnusOren** [comment]
I'll send update you on monday, when im back at work :D

**Comment by MagnusOren** [comment]
@MarkusBe Hi.
Here is my path to the files "/opt/netbox/venv/lib/python3.10/site-packages/netbox_qrcode"
I changed the utilities.py, to get the logo in the QR code, look for the "img = qr.make_image"
Netbox-qrcode uses python QR Code generator, to make the QR code. Here you have everything you need to change the QR code, and add logo. 
https://github.com/lincolnloop/python-qrcode/blob/main/README.rst#styled-image

Here is what i changed on my server, to get the logo in the QR Code, and other QR code style.

import base64
import qrcode

from io import BytesIO
from PIL import Image, ImageFont, ImageDraw

from qrcode.image.styledpil import StyledPilImage
from qrcode.image.styles.moduledrawers.pil import GappedSquareModuleDrawer, RoundedModuleDrawer, HorizontalBarsDrawer, VerticalBarsDrawer
from qrcode.image.styles.colormasks import RadialGradiantColorMask

from pkg_resources import resource_stream


def get_qr_with_text(qr, descr):
    dsi = get_qr_text(qr.size, descr)
    resimg = get_concat(qr, dsi)
    return get_img_b64(resimg)


def get_qr(text, **kwargs):
    qr = qrcode.QRCode(**kwargs)
    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_Q)
    qr.add_data(text)
    qr.make(fit=True)
    img = qr.make_image(image_factory=StyledPilImage, embeded_image_path="/opt/netbox/netbox/media/image-attachments/logoqrkode.png", module_drawer=HorizontalBarsDrawer())
    img = img.get_image()
    return img
