### ISSUE TITLE
Feature Request: Possible to add custom fields on "text_fields"

### ISSUE THREAD

**Issue by Bernardino18** [k01ek/netbox-qrcode#8]
Hi,
Thank you for the great work.

I want to suggest a configuration like this:

'text_fields': ['site', 'name', 'facility_id', 'tenant', 'custom_fields.field1', 'custom_fields.field2']

**Comment by k01ek** [comment]
HI @Bernardino18! 
Realisation of custom fields varies from release to release. I will try to code this functionality without locking to particular netbox version.

**Comment by Bernardino18** [comment]
There is already some progress in the development of this feature @k01ek ?

**Comment by k01ek** [comment]
@Bernardino18 Unfortunately, there is no progress at the time.

**Comment by k01ek** [comment]
This option now available in 0.0.5.
You can use 'text_fields': ['site', 'name', 'facility_id', 'tenant', 'cf.field1', 'cf.field2']

**Comment by k01ek** [comment]
https://github.com/k01ek/netbox-qrcode/commit/71229bb0fb25043900986cdc77e3060ba966eb62
