### ISSUE TITLE
Feat Request: QR code image to URL

### ISSUE THREAD

**Issue by Jasonlin1198** [k01ek/netbox-qrcode#9]
Hello! I've been trying to find a way to send the QR code image data into netbox custom fields, however, the plugin currently creates a URI which is not supported by netbox's fields. 

Is there a chance we can have an option for the QR code to be generated into a URL, and possibly have a way to get the PNG of the image?

**Comment by k01ek** [comment]
Hi @Jasonlin1198! Do you need to put the URL of the QR code image to the custom field of another object? What is your use case? Give me more details about what are you trying to achieve.

**Comment by Jasonlin1198** [comment]
Thanks for responding! My use case is that I am using Unreal Engine to fetch the QR code images from netbox by URL. I would need to get a given object's generated QR code based on an identifier (something like the object's name or id) through URL and not by base64 encoded URI. For example, something like https://url/device_1.png

Also, just wondering if it's possible for the plugin to iterate through all existing netbox devices and racks to create the QR code rather than on page load. This is so that for mass creation of these objects, the QR codes and QR code image URLs can be referenced without loading each object's web page.

**Comment by k01ek** [comment]
Ok, I got it. I understand what you want. This logic is opposite to what we have now in this plugin. The Image for QR Code dynamically generate when you open the appropriate object page, so the image does not store anywhere, and you can't get it by direct URL. I think it's not difficult to add the function which you need, but I need more time.
